version: 2.1

workflows:
  version: 2
  lint:
    jobs:
      - lint

jobs:
  lint:
    docker:
      - image: circleci/python:3.7
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Install Precommit
          command: sudo pip install pre-commit
      - run:
          name: Run Precommit
          command: pre-commit run --show-diff-on-failure --source origin/master --origin HEAD
      - save_cache:
          paths:
              - /home/circleci/.cache/pre-commit
          key: pre-commit-{{ checksum ".pre-commit-config.yaml" }}
